version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
